import sys, os, json, shutil
sys.path.insert(0, os.path.expanduser("~/.claude/skills/fedwiki-lib")); sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fedwiki
FARM = os.path.expanduser("~/Nextcloud/fedwiki/constitution.legalcommons.org")
PROV = "Claude Code, in dialogue with David Bovill, 2 September 2026"
def save(title, items, see, slug=None, assets=False, fork_from=None):
    slug = slug or fedwiki.as_slug(title)
    page = fedwiki.make_page(title, items, provenance=PROV)
    if assets: fedwiki.ensure_assets(page, f"pages/{slug}", journal=False)
    fedwiki.ensure_see(page, see, journal=False)
    if fork_from: page["journal"].append(fedwiki.fork_entry(fork_from))
    fedwiki.save_page(f"{FARM}/pages/{slug}", page); return slug

ROADMAP = """PALETTE cool

section Hosting and Style
2026-09-02 Hosting on the Pi5
2026-09-02..2026-09-05 Style Review

section Fragments and Subdomains
2026-09-04..2026-09-08 Fragment Ids
2026-09-06..2026-09-10 Subdomains

section Import
2026-09-10..2026-09-17 Constitution Register
2026-09-14..2026-09-24 Clause Library

section Languages and Drafting
2026-09-20..2026-10-10 Original Languages
2026-10-01..2026-10-31 Drafting Agent"""

plan = [
 "This page was written by [[Claude Code]] in dialogue with [[David Bovill]], 2 September 2026.",
 "The world's constitutions, one page each, on a public wiki — with every text cut into **fragments** that can be cited, spoken, and compared like for like across constitutions, and gathered into a **clause library** an agent can read when it helps us write a constitution of our own, before that constitution is compressed into a [[Poem]] and compiled into Lexon. The corpus is the [[Constitution Corpus]]; the mill that scores it is the [[Fragment Mill]] on the radio wiki; this plan is the import.",
 "The rule of this plan: **examples before hundreds.** Phase 1 is a gate. Nothing is generated in bulk until the page shape, the record, the fragment ids and the rights split have been looked at and approved.",
 "# Phase 0 — Hosting",
 "Every legalcommons.org site is served by the Pi5's public mirror, the same per-domain split as regovern.earth — the farm as a whole stays in cafe mode.",
 """- [x] Move the legalcommons.org apex and wildcard A records to the Pi5 (82.13.63.160), TTL 300
- [x] Confirm all 15 legalcommons sites serve from the Pi5 mirror with page counts matching the laptop
- [x] Create constitution.legalcommons.org — owner David, house theme, favicon, mirror restarted to enforce the owner""",
 "# Phase 1 — Style",
 "Three constitution pages and one clause page, generated by the same scripts that would generate hundreds, so what is approved is the generator, not a hand-made sample. Bhutan is small and open; Germany is medium and open; Bolivia is large and its translation is under a publisher's copyright, so its page shows the restricted shape.",
 """- [x] Three example constitution pages — [[Bhutan 2008]], [[Germany 1949 (rev. 2014)]], [[Bolivia (Plurinational State of) 2009]]
- [x] One example clause page — [[Unamendable Provisions]]
- [ ] David reviews the page structure, the Record item, the fragment id scheme and the rights split
- [ ] Amend the generators to the review and regenerate the four examples
- [ ] Approve — the gate opens""",
 "# Phase 2 — Fragments",
 "A constitution breaks along three grains, and each grain has a job. The **article** is the unit of citation — it is how the text names itself, and how every commentary already refers to it. The **paragraph** is the unit of speech — one thought, twelve to a hundred words, what a voice reads. The **topic key** is the unit of comparison — the Constitute ontology's 479 tags, applied section by section, which is what lets Bhutan's forest clause sit beside Norway's.",
 "Fragment ids follow the text's own numbering so they survive re-parsing and read aloud: `bhutan-2008:5.3` is Bhutan, 2008, Article 5, third paragraph; `germany-1949-rev-2014:79.3` is the eternity clause; `bolivia-2009:p.1` is the first paragraph of the preamble. Whole articles drop the paragraph. Runs of consecutive paragraphs take `a.b-c`. The same id names the same clause in every language.",
 "Fragments are **data, not pages**. A quarter of a million paragraphs cannot be wiki pages; they ride as `fragments.jsonl` on each constitution's page and as `{key}.jsonl` on each clause page. Only chosen fragments — the ones worth speaking, the ones a clause page shows — become items.",
 """- [ ] Freeze the id scheme on a [[Fragment Ids]] page with the edge cases decided — Roman numerals, lettered articles like 79a, unnumbered chapters, schedules and annexes
- [ ] Check generated ids against the Constitute Project's own article anchors on twenty constitutions
- [ ] Re-cut the corpus with ids and carry the score, topics and heading on every fragment
- [ ] Decide what a fragment page looks like for the few that earn one — the Fragment Mill's twenty first""",
 "# Phase 3 — Subdomains",
 "Proposal: three sites under the apex, each one label deep, per the [[Wiki Naming Convention]].",
 """- **constitution.legalcommons.org** — the register: one page per constitutional text, 240 pages, the corpus record, this plan
- **clause.legalcommons.org** — the library: one page per topic key, 479 pages, the same clause across every constitution, the drafting agent's reading
- **draft.legalcommons.org** — our own constitutions: the agent's proposals with citations, the human's edits, then Poem, then Lexon""",
 "Considered and set aside: one site for everything (search and the sitemap strain past several hundred pages, and the three audiences differ); one site per constitution (240 sites is machine-heavy and four labels deep). Cross-site links resolve by seeding fork events, as [[Fedwiki Interlink]] describes.",
 """- [ ] Decide the split
- [ ] Create clause.legalcommons.org and draft.legalcommons.org, owner David, theme and favicon
- [ ] Seed fork events so [[Unamendable Provisions]] resolves from a constitution page and back""",
 "# Phase 4 — Import",
 """- [ ] Generate the 240 constitution pages — 205 with full-text assets, 35 restricted with a SOURCE pointer only
- [ ] Generate the 479 clause pages, capped on the page with the full set as a data asset
- [ ] Write Welcome Visitors as the register — by region, by year, in force, superseded, draft
- [ ] Point the [[Fragment Mill]] at the register with a reference item
- [ ] Reindex, sweep red links, register the sites in wiki-sites""",
 "# Phase 5 — Languages",
 "Voices first: the Kokoro pack already speaks Spanish, French, Hindi, Italian, Japanese, Portuguese and Mandarin — but not German; Piper covers German and some thirty more. Texts second: the Constitute Project serves English, Spanish and Arabic; French, German, Japanese and Chinese originals come from their official publishers. The fragment id is the bridge — `japan-1946:9` is Article 9 in English and in Japanese alike.",
 """- [ ] Pull the Spanish and Arabic texts from Constitute for every constitution that has them
- [ ] Source the originals for French, German, Japanese and Chinese constitutions from official publishers, rights recorded
- [ ] Align originals by article so one fragment id resolves in every language it exists in
- [ ] Bench the non-English voices — Kokoro es, fr, ja, zh and Piper de — on the same clause in each language""",
 "# Phase 6 — Drafting",
 """- [ ] Write the drafting agent's brief: choose topics, read the clause library, propose clauses with fragment ids as citations
- [ ] Draft one constitution with it on draft.legalcommons.org, clause by clause, every clause traceable
- [ ] Compress the draft to a [[Poem]] on david.regovern.earth
- [ ] Compile the draft to Lexon on lexon.legalcommons.org""",
 "# Roadmap",
 {"type": "timeline", "text": ROADMAP},
]
save("Import Constitutions Plan", plan, ["[[Constitution Corpus]] · [[Fragment Mill]] · [[Radio Voice Plan]]", "[[Bhutan 2008]] · [[Germany 1949 (rev. 2014)]] · [[Bolivia (Plurinational State of) 2009]] · [[Unamendable Provisions]]"], assets=True)

# Constitution Corpus — forked from the radio wiki
src = json.load(open(os.path.expanduser("~/Code/radio-voice/mill/pages/constitution-corpus")))
page = dict(src); page["journal"] = list(src["journal"]) + [fedwiki.fork_entry("radio-agentic.private.fish")]
fedwiki.save_page(f"{FARM}/pages/constitution-corpus", page)

save("Welcome Visitors", [
 "Welcome to the **Constitution Commons** — the world's constitutions on a federated wiki, one page per text, cut into fragments that can be cited, spoken on the radio, and compared clause by clause across countries.",
 "This site is being built to the [[Import Constitutions Plan]]. Four example pages exist while the shape is reviewed: [[Bhutan 2008]], [[Germany 1949 (rev. 2014)]] and [[Bolivia (Plurinational State of) 2009]] show a constitution page in its open and restricted forms; [[Unamendable Provisions]] shows a clause page — the same clause in forty constitutions.",
 "The texts come from the [[Constitution Corpus]] — the Constitute Project's English editions, non-commercial use, attributed on every page. Fragments are scored for reading aloud by the [[Fragment Mill]] and spoken on Hitchhiker FM.",
 "# Sites",
 "- [[Import Constitutions Plan]] — the plan and its checkpoints\n- [[Constitution Corpus]] — coverage, API, rights\n- [[About]] — the site record",
], ["[[Import Constitutions Plan]] · [[About]]"], slug="welcome-visitors")

save("About", [
 "The site record for constitution.legalcommons.org, per the [[Wiki Naming Convention]]. This page is never renamed.",
 "# Site Record",
 {"type": "code", "language": "yaml", "text": "\n".join([
   "site: constitution.legalcommons.org", "host: pi5 (public mirror, /mnt/wikimedia/fedwiki)", "owner:", "  id: david", "  name: David Bovill",
   "purpose: the world's constitutions, one page per text, with fragments for citation, speech and comparison",
   "status: examples under review (Import Constitutions Plan, Phase 1)", "created: 2026-09-02",
   "twins: []", "siblings: [clause.legalcommons.org (proposed), draft.legalcommons.org (proposed)]",
   "source: Constitute Project, constituteproject.org, non-commercial use", "formerly: []"])},
], ["[[Import Constitutions Plan]] · [[Welcome Visitors]]"], slug="about")
print(sorted(os.listdir(f"{FARM}/pages")))
